name: Call workflow from Organisation repo
on:
  push:
    branches:
      - main
      - master
  jobs:
    test-workflow:
      uses: Github-Organisation-Test/workflows/.github/workflows/parentWorkflow.yml@main